[package]
name = "jackdots"
description = "Metering of JACK audio ports optimized for refreshable Braille displays"
version = "0.1.0"
authors = ["Mario Lang <mlang@blind.guru>"]
edition = "2018"

[dependencies]
clap = "2"
jack = "0.6"
ringbuf = "0.2"
rustfft = "3.0"
